# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='vote',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
