# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygames', '0002_auto_20171206_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamereview',
            options={'ordering': ['vote']},
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
