# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygames', '0003_auto_20171208_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamereview',
            options={},
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='vote',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='vote_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='vote_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
