# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygames', '0005_auto_20171208_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamereview',
            options={'ordering': ['-vote_likes']},
        ),
    ]
